import { ObjectCard, User } from '../types';

//export const CURRENT_USER: User = {
//  id: 'u1',
 // name: 'Алексей Петров',
//  role: 'editor',
//};

export const MOCK_OBJECTS: ObjectCard[] = [
  {
    id: '1',
    name: 'ЖК «Северный квартал»',
    shortName: 'Северный квартал',
    city: 'Москва',
    region: 'Московская область',
    address: 'ул. Северная, 12',
    yearDesign: '2020',
    yearRealized: '2023',
    projectStatus: 'Реализован',
    objectType: 'Жилой комплекс',
    customer: 'ООО «СтройГрупп»',
    inpadRole: 'Генеральный проектировщик',
    designStage: 'Сдан',
    areaObject: '45000',
    areaSite: '8500',
    floors: '22',
    shortDescription: 'Современный жилой комплекс с развитой инфраструктурой в северной части города.',
    fullDescription: 'Крупный жилой комплекс из трёх башенных секций высотой до 22 этажей. Предусмотрены подземная парковка, детский сад, коммерческие помещения на первых этажах.',
    totalArea: '45000',
    buildingArea: '3200',
    floorsCount: '22',
    buildingsCount: '3',
    parkingSpaces: '350',
    extraCharacteristics: [
      { key: 'Квартир', value: '486' },
      { key: 'Класс жилья', value: 'Комфорт' },
    ],
    mainImage: {
      id: 'img1',
      url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
      preview: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=300',
      caption: 'Фасад главного корпуса',
      order: 0,
      isMain: true,
      onSite: true,
      inPresentation: true,
      inPortfolio: true,
    },
    gallery: [],
    team: [
      { role: 'Руководитель проекта', name: 'Иванов А.В.' },
      { role: 'ГАП', name: 'Смирнова Е.Н.' },
    ],
    seoTitle: 'ЖК Северный квартал — ИнПАД',
    metaDescription: 'Жилой комплекс «Северный квартал» в Москве. Проект ИнПАД.',
    slug: 'severy-kvartal',
    ogImage: null,
    status: 'published',
    publicationStatus: 'published',
    updatedAt: '2024-03-15T10:30:00Z',
    createdAt: '2020-01-10T09:00:00Z',
  },
  {
    id: '2',
    name: 'Бизнес-центр «Меридиан»',
    shortName: 'Меридиан',
    city: 'Санкт-Петербург',
    region: 'Ленинградская область',
    address: 'Невский пр., 88',
    yearDesign: '2021',
    yearRealized: '',
    projectStatus: 'Строительство',
    objectType: 'Офисное здание',
    customer: 'АО «Инвест Девелопмент»',
    inpadRole: 'Генеральный проектировщик',
    designStage: 'Рабочая документация',
    areaObject: '28000',
    areaSite: '4200',
    floors: '16',
    shortDescription: 'Многофункциональный бизнес-центр класса А в историческом центре.',
    fullDescription: '',
    totalArea: '28000',
    buildingArea: '2100',
    floorsCount: '16',
    buildingsCount: '1',
    parkingSpaces: '120',
    extraCharacteristics: [],
    mainImage: {
      id: 'img2',
      url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
      preview: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=300',
      caption: 'Рендер фасада',
      order: 0,
      isMain: true,
      onSite: true,
      inPresentation: true,
      inPortfolio: false,
    },
    gallery: [],
    team: [
      { role: 'Руководитель проекта', name: 'Козлов П.М.' },
    ],
    seoTitle: '',
    metaDescription: '',
    slug: 'meridian-bc',
    ogImage: null,
    status: 'review',
    publicationStatus: 'pending',
    updatedAt: '2024-04-01T14:20:00Z',
    createdAt: '2021-06-15T11:00:00Z',
  },
  {
    id: '3',
    name: 'Спортивный комплекс «Олимп»',
    shortName: 'Олимп',
    city: 'Екатеринбург',
    region: 'Свердловская область',
    address: 'ул. Спортивная, 5',
    yearDesign: '2022',
    yearRealized: '',
    projectStatus: 'Проектирование',
    objectType: 'Спортивный объект',
    customer: 'Министерство спорта',
    inpadRole: 'Субподрядчик',
    designStage: 'Проектная документация',
    areaObject: '12000',
    areaSite: '25000',
    floors: '4',
    shortDescription: 'Многофункциональный спортивный комплекс с бассейном и ледовой ареной.',
    fullDescription: '',
    totalArea: '12000',
    buildingArea: '8000',
    floorsCount: '4',
    buildingsCount: '1',
    parkingSpaces: '200',
    extraCharacteristics: [
      { key: 'Вместимость', value: '3000 зрителей' },
    ],
    mainImage: null,
    gallery: [],
    team: [],
    seoTitle: '',
    metaDescription: '',
    slug: 'olimp-sport',
    ogImage: null,
    status: 'draft',
    publicationStatus: 'unpublished',
    updatedAt: '2024-04-10T16:45:00Z',
    createdAt: '2022-09-01T08:00:00Z',
  },
];

export function createEmptyObject(): ObjectCard {
  return {
    id: '',
    name: '',
    shortName: '',
    city: '',
    region: '',
    address: '',
    yearDesign: '',
    yearRealized: '',
    projectStatus: '',
    objectType: '',
    customer: '',
    inpadRole: '',
    designStage: '',
    areaObject: '',
    areaSite: '',
    floors: '',
    shortDescription: '',
    fullDescription: '',
    totalArea: '',
    buildingArea: '',
    floorsCount: '',
    buildingsCount: '',
    parkingSpaces: '',
    extraCharacteristics: [],
    mainImage: null,
    gallery: [],
    team: [],
    seoTitle: '',
    metaDescription: '',
    slug: '',
    ogImage: null,
    status: 'draft',
    publicationStatus: 'unpublished',
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  };
}
